image: "registry.gitlab.com/connorshea/suitecrm:latest"

variables:
  INSTANCE_URL: http://localhost
  DATABASE_DRIVER: MYSQL
  DATABASE_NAME: automated_tests
  DATABASE_HOST: mysql
  DATABASE_USER: automated_tests
  DATABASE_PASSWORD: automated_tests
  MYSQL_DATABASE: automated_tests
  MYSQL_USER: automated_tests
  MYSQL_ROOT_PASSWORD: automated_tests
  MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  INSTANCE_ADMIN_USER: admin
  INSTANCE_ADMIN_PASSWORD: admin1
  COMPOSER_MEMORY_LIMIT: -1

.default_before_script_template:
  before_script: &default_before_script_definition
    - ls
    - composer diagnose
    - composer install --no-plugins --no-scripts

.php_codecept_before_script_template:
  before_script: &php_codecept_before_script_definition
    - composer install --no-plugins --no-scripts
    # Run chromedriver in the background.
    - ../chromedriver --url-base=/wd/hub &
    - ./vendor/bin/codecept build
    # Create a symbolic link between the current directory and /var/www/html.
    - ln -s $(pwd) /var/www/html
    # Restart apache.
    - service apache2 restart

# Use anchors to reuse common configuration options.
# https://docs.gitlab.com/ee/ci/yaml/README.html#anchors
.php: &php
  services:
    # TODO: Add elasticsearch here as well.
    - mysql:5.7
  before_script: *php_codecept_before_script_definition
  script:
    # Run install wizard
    - ./vendor/bin/codecept run install --env travis-ci-hub -f -d --ext DotReporter
    - ./build/push_output.sh
    # Run API functional tests
    - ./vendor/bin/codecept run tests/api/V8/ -f -vvv
    # Run basic acceptance tests
    - ./vendor/bin/codecept run acceptance --env travis-ci-hub -f -vvv
  # Save 'var/log/apache2/error.log' and 'suitecrm.log' as artifacts
  # https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html
  artifacts:
    paths:
      - var/log/apache2/error.log
      - suitecrm.log
    expire_in: 2 weeks

php-lint:
  before_script: *default_before_script_definition
  script:
    - for file in $(git diff --name-status HEAD~1 HEAD | egrep "^[ACMR].*\.php$" | cut -c 3-); do php -l $file; done
  # Cache composer packages for reuse on the next run of the test suite.
  cache:
    # Set a key for the cache, e.g. based on the PHP version.
    key: 'php-lint'
    paths:
      - vendor/

php:7.2:
  <<: *php
  # Cache composer packages for reuse on the next run of the test suite.
  cache:
    # Set a key for the cache, e.g. based on the PHP version.
    key: 'php-7.2'
    paths:
      - vendor/
