image: "php:7.2.17-apache-stretch"

services:
  # Probably specify a version for mysql.
  - mysql
  # Add elasticsearch here as well.

variables:
  - INSTANCE_URL: http://localhost
  - DATABASE_DRIVER: MYSQL
  - DATABASE_NAME: automated_tests
  - DATABASE_HOST: localhost
  - DATABASE_USER: automated_tests
  - DATABASE_PASSWORD: automated_tests
  - INSTANCE_ADMIN_USER: admin
  - INSTANCE_ADMIN_PASSWORD: admin1
  - COMPOSER_MEMORY_LIMIT: -1

before_script:
  - php -v
  - curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
  - apt-get update -qqy && apt-get install -qqyy google-chrome-stable mysql-client composer
  - composer install

php-lint:
  script:
    # Put the actual lint command here:
    - php lint

# Use anchors to reuse common configuration options.
# https://docs.gitlab.com/ee/ci/yaml/README.html#anchors
.php:
  script:
    - ./vendor/bin/codecept run install --env travis-ci-hub -f -vvv
    # Run API functional tests
    - ./vendor/bin/codecept run tests/api/V8/ -f -vvv
    # Run basic acceptance tests
    - ./vendor/bin/codecept run acceptance --env travis-ci-hub -f -vvv
  # Save 'var/log/apache2/error.log' and 'suitecrm.log' as artifacts
  # https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html
  artifacts:
    paths:
      - var/log/apache2/error.log
      - suitecrm.log
    expire_in: 2 weeks

php-7.2:
  # Cache composer packages for reuse on the next run of the test suite.
  cache:
    # Set a key for the cache, e.g. based on the PHP version.
    key: 'php-7.2'
    paths:
      - vendor/
  <<: *php
